package dao;

import java.sql.*;
import model.*;

/**
 * Classe d'acces aux donnees contenues dans la table dominante
 * * @author ESIGELEC - TIC Department
 * @version 2.0
 */
public class DominanteDAO extends ConnectionDAO {

	/**
	 * Constructor
	 * 
	 */
	public DominanteDAO() {
		super();
	}
	
	/**
	 * Permet d'ajouter une dominante dans la table dominante.
	 * Le mode est auto-commit par defaut : chaque insertion est validee
	 * * @param dominante, la dominante a ajouter
	 * @return retourne le nombre de lignes ajoutees dans la table
	 */
	public int ajouterDominante(Dominante dominante) {
		Connection con = null;
		PreparedStatement ps = null;
		int returnValue = 0;

		try {	
			con = DriverManager.getConnection(URL, LOGIN, PASS);
					
			// 1. Préparation de l'insertion
			String sql = "INSERT INTO dominante(nom) VALUES(?)";
			
			// 2. Colonne générée
			String[] colonnesRetournees = { "idDominante" };
			ps = con.prepareStatement(sql, colonnesRetournees);
			
			// 3. Affectation des différentes valeurs  
			ps.setString(1, dominante.getNom());
		
			// 4. Execution de la requete
			returnValue = ps.executeUpdate();

			// 5. Récupération de la clé générée
			try (ResultSet rs = ps.getGeneratedKeys()) {
				if (rs.next()) {
					// Utilisation de setIdDominante pour être cohérent avec l'Update
					dominante.setId(rs.getInt(1));
				}
			}

		} catch (Exception e) {
			if (e.getMessage() != null && e.getMessage().contains("ORA-00001"))
				System.out.println("Cette Dominante existe déjà. Ajout impossible !");
			else
				e.printStackTrace();
		} finally {
			try { 
				if (ps != null) {
					ps.close();
				} 
			} catch (Exception ignore) {
			}
			try { 
				if (con != null) {
					con.close(); 
				} 
			} catch (Exception ignore) {}
		}
		return returnValue;
	}
	
	/**
	 * Permet de modifier une dominante dans la table dominante.
	 */
	public int update(Dominante dominante) {
		Connection con = null;
		PreparedStatement ps = null;
		int returnValue = 0;

		try {
			con = DriverManager.getConnection(URL, LOGIN, PASS);
			
			ps = con.prepareStatement("UPDATE dominante set nom = ? WHERE idDominante = ?");
			ps.setString(1, dominante.getNom());
			ps.setInt(2, dominante.getId());

			returnValue = ps.executeUpdate();

		} catch (Exception e) {
			e.printStackTrace();
		} finally {
			// fermeture du preparedStatement et de la connexion
			try {
				if (ps != null) {
					ps.close();
				}
			} catch (Exception ignore) {
			}
			try {
				if (con != null) {
					con.close();
				}
			} catch (Exception ignore) {}
		}
		return returnValue;
	}

	/**
	 * Permet de supprimer une dominante par id dans la table dominante.
	 */
	public int delete(int id) {
		Connection con = null;
		PreparedStatement ps = null;
		int returnValue = 0;

		try {
			con = DriverManager.getConnection(URL, LOGIN, PASS);
			
			ps = con.prepareStatement("DELETE FROM dominante WHERE idDominante = ?");
			ps.setInt(1, id);

			returnValue = ps.executeUpdate();

		} catch (Exception e) {
			if (e.getMessage() != null && e.getMessage().contains("ORA-02292")) {
				System.out.println("Cette dominante possede des sessions, suppression impossible !"
						+ " Supprimez d'abord ses sessions.");
			} else {
				e.printStackTrace();
			}
		} finally {
			try { if (ps != null) ps.close(); } catch (Exception ignore) {}
			try { if (con != null) con.close(); } catch (Exception ignore) {}
		}
		return returnValue;
	}

	public static void main(String[] args) throws SQLException {
		DominanteDAO dominanteDAO = new DominanteDAO();
		
		// Note : L'ID '3' sera écrasé par la base de données lors de l'insertion grâce au GENERATED BY DEFAULT.
		Dominante dominante = new Dominante("Cuisine2"); 
		dominanteDAO.ajouterDominante(dominante);
		
		System.out.println(dominante);
	}
}