-- Si les tables n'existent pas encore, un message d'erreur apparaît lors du DROP -- 
DROP TABLE Inscription;
DROP TABLE SessionEtu;
DROP TABLE Dominante;
DROP TABLE Campagne;
DROP TABLE Etudiant;
DROP TABLE Administrateur;

CREATE TABLE Administrateur (
    idAdministrateur INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(255) NOT NULL,
    prenom VARCHAR(255) NOT NULL,
    identifiantConnexion VARCHAR(255) NOT NULL UNIQUE,
    motDePasse VARCHAR(255) NOT NULL
);

CREATE TABLE Etudiant (
    idEtudiant INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(255) NOT NULL,
    prenom VARCHAR(255) NOT NULL,
    identifiantConnexion VARCHAR(255) NOT NULL UNIQUE,
    motDePasse VARCHAR(255) NOT NULL,
    promo INT NOT NULL
);

CREATE TABLE Campagne (
    idCampagne INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dateDebut DATE NOT NULL,
    dateFin DATE NOT NULL, 
    nbChoixMax INT NOT NULL,
    statut VARCHAR(255) NOT NULL,
    promotion INT NOT NULL
);

CREATE TABLE Dominante (
    idDominante INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(255) NOT NULL 
);

CREATE TABLE SessionEtu (
    idSession INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dateHeureDebut DATE NOT NULL, 
    dateHeureFin DATE NOT NULL,   
    capacite INT NOT NULL,
    idCampagne INT NOT NULL,
    idDominante INT NOT NULL,
    FOREIGN KEY (idCampagne) REFERENCES Campagne(idCampagne),
    FOREIGN KEY (idDominante) REFERENCES Dominante(idDominante)
);

CREATE TABLE Inscription (
    idInscription INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dateRealisee DATE NOT NULL,
    ordrePreference INT NOT NULL,
    statut VARCHAR(255) NOT NULL,
    idSession INT NOT NULL,
    idEtudiant INT NOT NULL,
    FOREIGN KEY (idSession) REFERENCES SessionEtu(idSession),
    FOREIGN KEY (idEtudiant) REFERENCES Etudiant(idEtudiant)
);